import { useEffect, useRef, useState } from 'react';
import type { AnalysisResult, AuthTab, Clause, Message, Risk } from './types';
import { DEMO_RESULT } from './demoData';

type FrontendUser = { email: string; user_metadata: { first_name: string } };
type User = FrontendUser;

const FAQ_DATA = [
  ['Is Clausify a replacement for a lawyer?', "No — and we're upfront about that. Clausify gives you clarity and highlights risks so you can have a better, more informed conversation with a lawyer. For high-stakes documents, always consult a qualified legal professional."],
  ['What types of documents can I analyse?', "Employment contracts, NDAs, rental agreements, freelance contracts, terms of service, loan agreements, and most other standard legal documents. If it's text, Clausify can read it."],
  ['Is my document stored anywhere?', 'Once you sign up and sign in, your documents are securely saved to your account so you can revisit past analyses at any time. Your privacy is always protected — we never share your documents with third parties.'],
  ['How accurate is the risk flagging?', "Clausify uses Claude — one of the most capable AI models available — to identify unusual, one-sided, or potentially harmful clauses. It's highly accurate for common contract types, though edge cases and very jurisdiction-specific clauses may need human review."],
  ['Does it work on scanned documents?', 'Yes. Upload a JPEG or PNG of a scanned contract and Clausify will read and analyse it. For best results, ensure the scan is clear and legible.'],
  ['Is it really free?', 'Yes — completely free to use right now. No sign-up, no credit card, no limits. We may introduce a premium tier in the future for advanced features.'],
] as const;

const HOW_STEPS = [
  ['01', 'upload', 'Upload your document', 'Drop in a PDF, JPEG, or PNG — or paste the text directly. Clausify handles any format.'],
  ['02', 'search', 'AI reads every clause', 'Claude analyses the full document — not just summaries — identifying risk, intent, and unusual language.'],
  ['03', 'alert', 'Risks highlighted inline', 'High, medium, and low risk clauses are colour-coded directly inside the document text. Nothing hidden.'],
  ['04', 'chat', 'Ask anything', 'A live chat assistant answers your questions about the document in plain English. No legal jargon.'],
] as const;

const LOADING_STEPS = ['Reading document structure...', 'Identifying key clauses...', 'Flagging risk areas...', 'Generating plain-English summary...', 'Preparing your report...'];

type FileState = { file: File | null; title: string; subtitle: string };

function Icon({ type }: { type: string }) {
  const paths: Record<string, React.ReactNode> = {
    upload: <><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></>,
    search: <><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></>,
    alert: <><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></>,
    chat: <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>,
  };
  return <svg width="18" height="18" fill="none" stroke="var(--gold2)" strokeWidth="2" strokeLinecap="round" viewBox="0 0 24 24">{paths[type]}</svg>;
}

function scrollToId(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); }

function AuthModal({ initialTab, onClose }: { initialTab: AuthTab; onClose: () => void }) {
  const [tab, setTab] = useState<AuthTab>(initialTab);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);
  const [loading, setLoading] = useState(false);
  const [form, setForm] = useState({ first: '', last: '', email: '', phone: '', password: '' });
  const update = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement>) => setForm({ ...form, [key]: event.target.value });
  const friendly = (message: string) => message.includes('Invalid login') ? 'Incorrect email or password. Please try again.' : message.includes('Email not confirmed') ? 'Please confirm your email before signing in.' : message.includes('already registered') ? 'An account with this email already exists. Sign in instead.' : message;

  async function signIn() {
    if (!form.email || !form.password) { setError('Please enter your email and password.'); return; }
    setLoading(true); window.setTimeout(() => { setLoading(false); onClose(); }, 400);
  }
  async function signUp() {
    if (!form.first || !form.last || !form.email || !form.phone) { setError('Please fill in all fields.'); return; }
    if (form.password.length < 8) { setError('Password must be at least 8 characters.'); return; }
    setLoading(true); window.setTimeout(() => { setLoading(false); setSuccess(true); }, 400);
  }
  async function forgotPassword() {
    if (!form.email) { setError('Enter your email address above first.'); return; }
    setError('Reset link preview ready — backend connection will be added later.');
  }
  return <div id="auth-modal-overlay" className="show" onClick={(event) => event.target === event.currentTarget && onClose()}>
    <div className="auth-modal" role="dialog" aria-modal="true" aria-label="Sign in">
      <button className="auth-close" onClick={onClose} aria-label="Close">×</button>
      <div className="auth-logo">Claus<em>ify</em></div>
      <p className="auth-modal-subtitle">{tab === 'signin' ? 'Sign in to your account' : 'Create your free account'}</p>
      <div className="auth-tabs"><button className={`auth-tab ${tab === 'signin' ? 'on' : ''}`} onClick={() => { setTab('signin'); setError(''); }}>Sign in</button><button className={`auth-tab ${tab === 'signup' ? 'on' : ''}`} onClick={() => { setTab('signup'); setError(''); }}>Create account</button></div>
      {success ? <div className="auth-confirm"><div className="auth-confirm-icon">✓</div><h3>Check your inbox</h3><p>We sent a confirmation link to <strong>{form.email}</strong>. Click the link to activate your account.</p><button className="auth-btn-primary" style={{ marginTop: 18 }} onClick={() => { setSuccess(false); setTab('signin'); }}>Back to sign in</button></div> : tab === 'signin' ? <div id="auth-signin-form">
        <Field label="Email address"><input type="email" placeholder="you@example.com" autoComplete="email" value={form.email} onChange={update('email')} /></Field>
        <Field label="Password"><input type="password" placeholder="Enter your password" autoComplete="current-password" value={form.password} onChange={update('password')} /></Field>
        <div className="auth-error show">{error}</div><div className="auth-forgot" onClick={forgotPassword}>Forgot password?</div><button className="auth-btn-primary" disabled={loading} onClick={signIn}>{loading ? 'Please wait...' : 'Sign in'}</button><AuthDivider /><GoogleButton /><p className="auth-switch">Don't have an account? <a onClick={() => setTab('signup')}>Sign up</a></p>
      </div> : <div id="auth-signup-form">
        <div className="auth-name-row"><Field label="First name"><input placeholder="Priya" autoComplete="given-name" value={form.first} onChange={update('first')} /></Field><Field label="Last name"><input placeholder="Sharma" autoComplete="family-name" value={form.last} onChange={update('last')} /></Field></div>
        <Field label="Email address"><input type="email" placeholder="you@example.com" autoComplete="email" value={form.email} onChange={update('email')} /></Field><Field label="Phone number"><div className="auth-phone-row"><span className="auth-phone-prefix">+91</span><input type="tel" placeholder="98765 43210" maxLength={10} value={form.phone} onChange={update('phone')} /></div></Field><Field label="Password"><input type="password" placeholder="At least 8 characters" autoComplete="new-password" value={form.password} onChange={update('password')} /></Field>
        <div className="auth-error show">{error}</div><button className="auth-btn-primary" disabled={loading} onClick={signUp}>{loading ? 'Please wait...' : 'Create account'}</button><AuthDivider /><GoogleButton /><p className="auth-switch">Already have an account? <a onClick={() => setTab('signin')}>Sign in</a></p>
      </div>}
    </div>
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="auth-field"><label>{label}</label>{children}</div>; }
function AuthDivider() { return <div className="auth-or"><div className="auth-or-line"/><span>or</span><div className="auth-or-line"/></div>; }
function GoogleButton() { return <button className="auth-btn-google" onClick={() => undefined}>Continue with Google</button>; }

function Navigation({ user, onAuth }: { user: User | null; onAuth: (tab: AuthTab) => void }) {
  const [open, setOpen] = useState(false); const name = user?.user_metadata?.first_name || user?.email?.split('@')[0] || ''; const initial = name.charAt(0).toUpperCase();
  return <nav className="visible"><div className="nav-logo" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>Claus<span>ify</span></div><div className="nav-center"><a className="nav-link" onClick={() => scrollToId('hero')}>Home</a><a className="nav-link" onClick={() => scrollToId('how')}>How it works</a><a className="nav-link" onClick={() => scrollToId('tool')}>Analyse</a><a className="nav-link" onClick={() => scrollToId('faq')}>FAQ</a></div><div className="nav-right">{!user ? <button className="btn-signin" onClick={() => onAuth('signin')}>Sign in</button> : <div id="nav-user-menu" style={{ display: 'flex' }}><div className="nav-avatar" onClick={() => setOpen(!open)}>{initial}</div><div className={`nav-user-dropdown ${open ? 'open' : ''}`}><div className="dropdown-name">{name}</div><div className="dropdown-email">{user.email}</div><div className="dropdown-divider"/><div className="dropdown-item">Sign out</div></div></div>}</div></nav>;
}

function Hero() { return <><section id="hero"><div className="hero-glow"/><div className="hero-eyebrow reveal in"><div className="hero-eyebrow-dot"/>AI-Powered Legal Analysis</div><h1 className="hero-title reveal in reveal-delay-1">Know what you're<br/><em>signing.</em> <strong>Before</strong><br/>you sign it.</h1><p className="hero-sub reveal in reveal-delay-2">Upload any contract and get a plain-English summary, colour-coded risk flags, and a live chat assistant — in under 30 seconds.</p><div className="hero-btns reveal in reveal-delay-3"><button className="btn-primary" onClick={() => scrollToId('tool')}>Analyse a document →</button><button className="btn-ghost" onClick={() => scrollToId('how')}>See how it works</button></div><div className="hero-trust reveal in reveal-delay-4"><span>Sign up to analyse</span><div className="trust-divider"/><span>Plain English, always</span><div className="trust-divider"/><span>Powered by Claude AI</span></div></section><div className="divider-line"/></>; }
function HowItWorks() { return <><section id="how"><div className="section"><div className="section-eyebrow reveal">How it works</div><h2 className="section-title reveal reveal-delay-1">Four steps.<br/>Total clarity.</h2><p className="section-body reveal reveal-delay-2">No legal degree required. No jargon. Just the truth about what you're signing — fast.</p><div className="how-grid">{HOW_STEPS.map(([num, icon, title, desc], index) => <div className={`how-card reveal reveal-delay-${index + 1}`} key={num}><div className="how-num">{num}</div><div className="how-icon"><Icon type={icon}/></div><div className="how-title">{title}</div><div className="how-desc">{desc}</div></div>)}</div></div></section><div className="divider-line"/></>; }

function UploadTool({ user, onAuth }: { user: User | null; onAuth: (tab: AuthTab) => void }) {
  const [fileState, setFileState] = useState<FileState>({ file: null, title: 'Drop your document here', subtitle: 'Click to browse — PDF, JPEG or PNG' }); const [paste, setPaste] = useState(''); const [loading, setLoading] = useState(false); const [step, setStep] = useState(LOADING_STEPS[0]); const [result, setResult] = useState<AnalysisResult | null>(null); const [error, setError] = useState(''); const [docContext, setDocContext] = useState(''); const fileInput = useRef<HTMLInputElement>(null);
  const selectFile = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) setFileState({ file, title: file.name, subtitle: `${(file.size / 1024).toFixed(0)} KB · Ready to analyse` }); };
  async function analyse() { if (!paste.trim() && !fileState.file) { setError('Please upload a file or paste text first.'); return; } setError(''); setLoading(true); let timer = 0; const interval = window.setInterval(() => { setStep(LOADING_STEPS[Math.min(++timer, LOADING_STEPS.length - 1)]); }, 700); try { const text = paste.trim() || await extractText(fileState.file!); if (!text.trim()) throw new Error('No text could be extracted from the file. Try pasting the text directly.'); setDocContext(text); await new Promise((resolve) => window.setTimeout(resolve, 1200)); setResult(DEMO_RESULT); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not read the selected file.'); } finally { window.clearInterval(interval); setLoading(false); } }
  function reset() { setResult(null); setPaste(''); setError(''); setFileState({ file: null, title: 'Drop your document here', subtitle: 'Click to browse — PDF, JPEG or PNG' }); if (fileInput.current) fileInput.current.value = ''; }
  return <section id="tool"><div className="section"><div className="section-eyebrow reveal">The tool</div><h2 className="section-title reveal reveal-delay-1">Try it now.</h2><div className="tool-wrap reveal reveal-delay-2" style={{ marginTop: 40 }}>{loading ? <div className="tool-loading show"><div className="ring"/><div className="load-title">Analysing your document</div><div className="load-step">{step}</div></div> : result ? <Results result={result} docContext={docContext} onReset={reset}/> : <div><div className="tool-header"><div className="tool-header-left"><h2>Analyse your document</h2><p>Upload or paste — results in under 30 seconds</p></div></div><div className="tool-body"><div className="upload-area" style={fileState.file ? { borderColor: 'var(--gold-bdr)', background: 'var(--gold-dim)' } : undefined}><input ref={fileInput} type="file" accept=".pdf,.jpg,.jpeg,.png,.txt" onChange={selectFile}/><div className="upload-icon-wrap"><Icon type="upload"/></div><div className="upload-title">{fileState.title}</div><div className="upload-sub" style={error ? { color: 'var(--high)' } : undefined}>{error || fileState.subtitle}</div><div className="fmt-tags"><span className="fmt-tag">PDF</span><span className="fmt-tag">JPEG</span><span className="fmt-tag">PNG</span></div></div><div className="or-row"><div className="or-line"/><span className="or-text">or paste text</span><div className="or-line"/></div><textarea value={paste} onChange={(event) => setPaste(event.target.value)} placeholder="Paste your contract text here..."/><button className="analyse-btn" onClick={analyse}>Analyse document →</button></div></div>}</div></div></section>;
}

function Results({ result, docContext, onReset }: { result: AnalysisResult; docContext: string; onReset: () => void }) { const [tab, setTab] = useState<'hl' | 'cl'>('hl'); return <div className="results show"><div className="tool-header"><div className="tool-header-left"><h2>Analysis complete</h2><p>Here's what we found</p></div><div className="new-doc-btn" onClick={onReset}>← New document</div></div><div className="tool-body"><div className="res-card"><div className="card-label">Plain English Summary</div><div className="summary-text">{result.summary}</div></div><RiskBanner result={result}/><div className="doc-card"><div className="doc-tabs"><div className={`d-tab ${tab === 'hl' ? 'on' : ''}`} onClick={() => setTab('hl')}>Highlighted document</div><div className={`d-tab ${tab === 'cl' ? 'on' : ''}`} onClick={() => setTab('cl')}>Risk clauses</div></div>{tab === 'hl' ? <><div className="doc-body">{highlightedNodes(result.highlightedDoc)}</div><div className="legend"><Legend color="var(--high)" text="High risk"/><Legend color="var(--med)" text="Review carefully"/><Legend color="var(--low)" text="Standard clause"/></div></> : <div className="clause-list">{result.clauses.map((clause) => <ClauseItem clause={clause} key={clause.name}/>)}</div>}</div><Chat context={docContext} clauses={result.clauses}/></div></div>; }
function RiskBanner({ result }: { result: AnalysisResult }) { const risk = result.riskLevel === 'medium' || result.riskLevel === 'med' ? 'med' : result.riskLevel; return <div className="risk-banner"><div className="risk-score-wrap"><div className="risk-eyebrow-label">Overall Risk</div><div className={`risk-score-big ${risk}`}>{result.riskLevel.toUpperCase()}</div></div><div className="risk-bar-area"><div className="bar-meta"><span>Low</span><span>High</span></div><div className="bar-track"><div className="bar-fill" style={{ width: `${result.riskScore}%`, background: `var(--${risk === 'med' ? 'med' : risk})` }}/></div><div className="risk-desc-text">{result.riskSummary}</div></div></div>; }
function Legend({ color, text }: { color: string; text: string }) { return <div className="leg"><div className="leg-sq" style={{ background: color }}/>{text}</div>; }
function ClauseItem({ clause }: { clause: Clause }) { return <div className="clause"><div className="clause-top"><span className={`chip ${clause.risk}`}>{clause.risk === 'high' ? 'High risk' : clause.risk === 'med' ? 'Review' : 'Standard'}</span><span className="clause-name">{clause.name}</span></div><div className="clause-desc">{clause.explanation}</div></div>; }
function highlightedNodes(value: string) { return value.split(/(<HL class="(?:high|med|low)">[^<]*<\/HL>)/g).map((part, index) => { const match = part.match(/^<HL class="(high|med|low)">([^<]*)<\/HL>$/); return match ? <span className={`hl ${match[1]}`} key={index}>{match[2]}</span> : <span key={index}>{part.split('\n').flatMap((line, lineIndex, lines) => [line, lineIndex < lines.length - 1 && <br key={`${index}-${lineIndex}`}/>])}</span>; }); }
function Chat({ context: _context, clauses }: { context: string; clauses: Clause[] }) { const [messages, setMessages] = useState<Message[]>([{ role: 'assistant', content: `I've finished analysing your document. I found ${clauses.filter((clause) => clause.risk === 'high').length} high-risk clauses. What would you like to understand better?` }]); const [input, setInput] = useState(''); const suggestions = ['What are my biggest risks?', 'Can I negotiate this?', 'Explain the termination clause', 'Is this standard?']; async function send(question = input) { const value = question.trim(); if (!value) return; setInput(''); setMessages((current) => [...current, { role: 'user', content: value }, { role: 'assistant', content: 'Thinking...' }]); await new Promise((resolve) => window.setTimeout(resolve, 500)); setMessages((current) => [...current.slice(0, -1), { role: 'assistant', content: 'This frontend preview is ready for your question. Backend-powered answers will be connected in the next phase.' }]); } return <div className="chat-card"><div className="chat-head"><div className="chat-head-icon"><Icon type="chat"/></div><div><div className="chat-head-title">Ask about this document</div><div className="chat-head-sub">Frontend preview</div></div></div><div className="chat-msgs">{messages.map((message, index) => <div className={`msg ${message.role === 'assistant' ? 'ai' : 'user'}`} key={`${message.role}-${index}`}>{message.content}</div>)}</div><div className="suggs">{suggestions.map((suggestion) => <div className="sugg" onClick={() => send(suggestion)} key={suggestion}>{suggestion}</div>)}</div><div className="chat-input-row"><input className="chat-input" value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && send()} placeholder="Ask anything about this document..."/><button className="send-btn" onClick={() => send()}>Send</button></div></div>; }

async function extractText(file: File) { const name = file.name.toLowerCase(); if (name.endsWith('.txt') || file.type === 'text/plain') return file.text(); if (name.endsWith('.pdf') || file.type === 'application/pdf') { const pdfjs = await loadExternal('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js', 'pdfjsLib') as any; pdfjs.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'; const pdf = await pdfjs.getDocument({ data: await file.arrayBuffer() }).promise; let text = ''; for (let pageNumber = 1; pageNumber <= pdf.numPages; pageNumber++) { const page = await pdf.getPage(pageNumber); const content = await page.getTextContent(); text += content.items.map((item: { str?: string }) => item.str || '').join(' ') + '\n\n'; } return text.trim(); } if (/\.(jpg|jpeg|png)$/.test(name) || /image\/(jpeg|png)/.test(file.type)) { const tesseract = await loadExternal('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js', 'Tesseract') as any; const { data } = await tesseract.recognize(file, 'eng'); return (data.text || '').trim(); } throw new Error('Unsupported file type. Use PDF, JPEG, PNG, or paste text.'); }
function loadExternal(src: string, globalName: string) { return new Promise((resolve, reject) => { const existing = (window as unknown as Record<string, unknown>)[globalName]; if (existing) return resolve(existing); const script = document.createElement('script'); script.src = src; script.onload = () => resolve((window as unknown as Record<string, unknown>)[globalName]); script.onerror = () => reject(new Error(`Failed to load ${src}`)); document.head.appendChild(script); }); }
function FAQ() { const [open, setOpen] = useState<number | null>(null); return <><section id="faq"><div className="section section-sm"><div className="section-eyebrow reveal">FAQ</div><h2 className="section-title reveal reveal-delay-1">Questions,<br/>answered plainly.</h2><div className="faq-list reveal reveal-delay-2">{FAQ_DATA.map(([question, answer], index) => <div className={`faq-item ${open === index ? 'open' : ''}`} key={question}><div className="faq-q" onClick={() => setOpen(open === index ? null : index)}><span>{question}</span><svg className="faq-chevron" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="6 9 12 15 18 9"/></svg></div><div className="faq-a">{answer}</div></div>)}</div></div></section><div className="divider-line"/></>; }

export default function App() { const [loader, setLoader] = useState(true); const [authTab, setAuthTab] = useState<AuthTab | null>(null); useEffect(() => { const timer = window.setTimeout(() => setLoader(false), 2400); return () => window.clearTimeout(timer); }, []); useEffect(() => { if (authTab) document.body.style.overflow = 'hidden'; else document.body.style.overflow = ''; return () => { document.body.style.overflow = ''; }; }, [authTab]); useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.target.classList.toggle('in', entry.isIntersecting)), { threshold: 0.12 }); document.querySelectorAll('.reveal').forEach((element) => observer.observe(element)); return () => observer.disconnect(); }, [loader]); return <><div id="loader" className={loader ? '' : 'hide'}><div className="loader-logo"><span className="plain">Claus</span><span className="stroke">ify</span></div><div className="loader-line"/></div><Navigation user={null} onAuth={setAuthTab}/><main><Hero/><HowItWorks/><UploadTool user={null} onAuth={setAuthTab}/><div className="divider-line"/><FAQ/></main><footer><div className="footer-logo">Claus<span>ify</span></div><div className="footer-note">AI legal analysis · Not a substitute for legal advice · © 2025 Clausify</div></footer>{authTab && <AuthModal initialTab={authTab} onClose={() => setAuthTab(null)}/>}</>; }
